# Apache settings ######################################################################################################
apache_create_vhosts: "true"
apache_listen_ip: "*"
apache_packages_state: "latest"
apache_remove_default_vhost: "true"
apache_vhosts:
  - servername: "null"
    serveralias: "*"
    documentroot: "{{ server_document_root }}"
    extra_parameters: |
      RewriteCond %{HTTP_HOST} !^www\. [NC]
      RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
apache_vhosts_ssl:
  - servername: "null"
    serveralias: "*"
    documentroot: "{{ server_document_root }}"
    certificate_file: "/etc/ssl/dev.crt"
    certificate_key_file: "/etc/ssl/dev.key"
    extra_parameters: |
      RewriteCond %{HTTP_HOST} !^www\. [NC]
      RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

# MySQL settings #######################################################################################################
mysql_user_home: "/root"
mysql_user_name: "root"
mysql_user_password: "root"
mysql_root_home: "/root"
mysql_root_username: "root"
mysql_root_password: "root"
mysql_user_password_update: "yes"
overwrite_global_mycnf: "yes"

# NFS settings #########################################################################################################
nfs_exports:
  - "# *               - anyone on the network can access this share"
  - "# all_squash      - all network access to the shared folder will be considered as having come from anonguid and anongid"
  - "# anonuid         - set to {{ apache_group_id }} the {{ apache_group }} user"
  - "# anongid         - set to {{ apache_group_id }} the {{ apache_group }} group"
  - "# no_root_squash"
  - "{{ server_document_root }}    *(rw,sync,insecure,nohide,no_subtree_check,fsid=0,crossmnt,all_squash,anonuid={{ apache_group_id }},anongid={{ apache_group_id }})"

# nginx settings #########################################################################################################
nginx_remove_default_vhost: "true"

# NodeJS settings ######################################################################################################
npm_config_prefix: "/usr"
nodejs_install_npm_user: "root"
nodejs_npm_global_packages:
  - "diff-so-fancy"
  - "sass"
  - "uglifycss"
  - "uglify-js"

# PHP settings #########################################################################################################
php_date_timezone: "{{ server_timezone }}"
php_disable_functions:
  - "pcntl_alarm"
  - "pcntl_fork"
  - "pcntl_waitpid"
  - "pcntl_wait"
  - "pcntl_wifexited"
  - "pcntl_wifstopped"
  - "pcntl_wifsignaled"
  - "pcntl_wexitstatus"
  - "pcntl_wtermsig"
  - "pcntl_wstopsig"
  - "pcntl_signal_dispatch"
  - "pcntl_get_last_error"
  - "pcntl_strerror"
  - "pcntl_sigprocmask"
  - "pcntl_sigwaitinfo"
  - "pcntl_sigtimedwait"
  - "pcntl_exec"
  - "pcntl_getpriority"
  - "pcntl_setpriority"
php_html_errors: "False"
php_install_recommends: "yes"
php_memcached_package: "php-memcached"
php_memory_limit: "512M"
php_mysql_package: "php-mysql"
php_opcache_load_comments: "1"
php_opcache_save_comments: "1"
php_packages:
  - "php"
  - "php-apcu"
  - "php-cli"
  - "php-common"
  - "php-curl"
  - "php-gd"
  - "php-intl"
  - "php-json"
  - "php-mbstring"
  - "php-opcache"
  - "php-pear"
  - "php-pspell"
  - "php-soap"
  - "php-readline"
  - "php-xml"
  - "php-xsl"
php_post_max_size: "50M"
php_session_gc_maxlifetime: "2592000"
php_session_gc_probability: "1"
php_upload_max_filesize: "50M"
php_variables_order: "EGPCS"
php_version: "{{ server_php_version }}"
php_xdebug_idekey: "xdebug.ide"
php_xdebug_remote_autostart: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_enable: "true"
php_xdebug_remote_log: "{{ server_document_root }}/xdebug-remote.log"
php_xdebug_remote_port: "9000"

# Server settings ######################################################################################################
server_timezone: "America/Vancouver"
server_document_root: "/var/www"

# SSL keys #############################################################################################################
ssl_crt_data: |
  -----BEGIN CERTIFICATE-----
  MIIFQjCCAyoCCQDwvBGjWkY99zANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJD
  QTELMAkGA1UECAwCQkMxGDAWBgNVBAcMD05ldyBXZXN0bWluc3RlcjERMA8GA1UE
  CgwITXVnbyBXZWIxGjAYBgkqhkiG9w0BCQEWC2RldkBtdWdvLmNhMB4XDTE5MDkw
  OTIxMDU0M1oXDTQ3MDEyNDIxMDU0M1owYzELMAkGA1UEBhMCQ0ExCzAJBgNVBAgM
  AkJDMRgwFgYDVQQHDA9OZXcgV2VzdG1pbnN0ZXIxETAPBgNVBAoMCE11Z28gV2Vi
  MRowGAYJKoZIhvcNAQkBFgtkZXZAbXVnby5jYTCCAiIwDQYJKoZIhvcNAQEBBQAD
  ggIPADCCAgoCggIBAKF2sD+4NJsREJQ8anjYYDUhRd8oGAXotUOuKAB+r3urGwXY
  ADppbj29+re271zpBSGPKIc3v0peUyHQDpPNAufPymKWvFZRMmGJwmvY/oq8E6i+
  sScldr4m+FL4nR1MHpjpcwh1hPzwvuMhZBtF2UkK3kB31iSvcSMa63/KDTT92qaC
  tmQ7uaSUVWj/NFox235Qoz6kwoxu54ylYe4ykM88nbcUZIPNAKR6ORfBIiHp/qZo
  NUrv048CEhO6DFske1YwLqkAPA8N7llT+HYRIiFtFkzO9kaL7sMtoA762fuqAP3q
  +YIhlT8kBRqo5K/D28jMtU1HutBli2Q9/stkmzJgbeYnhAVCTrBE9CMrzSSjvJfD
  YkRTnMc11ElwN97ZV0RRYHcq0S0OrdgEZxUGZmIiHmRQu+nd6P//t4fbz4hpAxkZ
  30jGFn5e0qZMMqfihizbqzIrIhRlZNW8rC/1N8QCwB0rMLPEx6BOXr64mxNlWc7V
  SMjT9ym6aOdp0QHfrhxG8MfOqr9z0I7b4r4MhsAlCOVxF2HejazJQi0uuCLe23HG
  CmQxYzyF1MmZsK7hR1RnnRt+/7ngrUjMvjlvNulUeWk163BgJTiNMzvjqD8AhsDC
  YKLyt6Q8TMc3FtkP/Tq4ObUvEeHeDzQ+x0Ad2rYu1Akgbbia9vI+KYYBqyzfAgMB
  AAEwDQYJKoZIhvcNAQELBQADggIBAHuun3/F58g9YtkWYvahkKTl9fQcW+AqorSZ
  +E/0yLzA1nspwdxIbqS7kI2XPZfSGXE4Ht9lgQTNz6x4sQruVbvrdNdNr5hYI9Xo
  C0OFmbucuefSC6ItYpIEnQxR8MNnzZ1QdzpIX5v7AVuedeY5qtsegrO0K+ZoUZ5f
  DBKQ6xlYWMvf9msm2IAfzr9Y4M9fH+EFLbxLvgyQbsO06n7dQ3nPDnPkYqq7/4GB
  F0hvJwb2+yqGDboLtx7w/UGvQrUeLAWEPDGaM+l4VWoZmN02mAF5B65h3BB/Yhkt
  bS285RXn4m9FkQAZPq1/5kDvYvXbyaOKfoZqE8TytIe22UyqlOBcgfhyZjNpyyqS
  WI3mUobjWhRsjO2Bild/H/XZ86x1H5MP1DXj5UKsvwQebRko1825OluoE05oIEwj
  ozh5cafjeL8nRhQtOY4TqpYCmfrJpt1Ds8DpLV9MJWWjmdYIM8iczrSvl3TFsd+G
  +HDawYQtR0x0WGeE0aS82vfuP0lxYCOYwiB3FnZu4+4anL5yCpeBYYN3p8NGsHin
  xdXLgqIcaRAukB7UvIWjbDQOHGMeUheKeGtATWYtZoVg1W01kOLQoqKdFpHIuk9f
  YNi+gJM4X60IivMf9/k/AobaYc6u4UJ/+vvlR1HM1WS6jXRxe7wqzuFXUs77EZ/K
  ieBMyPlp
  -----END CERTIFICATE-----

ssl_key_data: |
  -----BEGIN PRIVATE KEY-----
  MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQChdrA/uDSbERCU
  PGp42GA1IUXfKBgF6LVDrigAfq97qxsF2AA6aW49vfq3tu9c6QUhjyiHN79KXlMh
  0A6TzQLnz8pilrxWUTJhicJr2P6KvBOovrEnJXa+JvhS+J0dTB6Y6XMIdYT88L7j
  IWQbRdlJCt5Ad9Ykr3EjGut/yg00/dqmgrZkO7mklFVo/zRaMdt+UKM+pMKMbueM
  pWHuMpDPPJ23FGSDzQCkejkXwSIh6f6maDVK79OPAhITugxbJHtWMC6pADwPDe5Z
  U/h2ESIhbRZMzvZGi+7DLaAO+tn7qgD96vmCIZU/JAUaqOSvw9vIzLVNR7rQZYtk
  Pf7LZJsyYG3mJ4QFQk6wRPQjK80ko7yXw2JEU5zHNdRJcDfe2VdEUWB3KtEtDq3Y
  BGcVBmZiIh5kULvp3ej//7eH28+IaQMZGd9IxhZ+XtKmTDKn4oYs26syKyIUZWTV
  vKwv9TfEAsAdKzCzxMegTl6+uJsTZVnO1UjI0/cpumjnadEB364cRvDHzqq/c9CO
  2+K+DIbAJQjlcRdh3o2syUItLrgi3ttxxgpkMWM8hdTJmbCu4UdUZ50bfv+54K1I
  zL45bzbpVHlpNetwYCU4jTM746g/AIbAwmCi8rekPEzHNxbZD/06uDm1LxHh3g80
  PsdAHdq2LtQJIG24mvbyPimGAass3wIDAQABAoICADM4aZTtJJMEiNPdjpEjYvG3
  ymiOWYCWX9pGhx4REi4TC5GBAiGFjJk9iSl6eNhqe1w4A81RW/eFkK2rSNSONpu/
  CR7ZXomrXGYgw3Je9fCg1UO0qpIWimKsDh6UC5NdsF8lv34xeayb2pJG53DXaaSI
  NBUTbvVYSnWudoKlYCctWI117dJCOBQDkkyqmLr8EfsyLXcT4TuXexDc7gIYPGPh
  gM6xQ2mkQM3sj+v/Moq7pjK34CATkHNPXtivLnhDTHT89/BYyLSl4LSptKoPqVod
  NvPKu8mJXobAFIRsA3aYaZQjVF95s9TB4nSgm1s+sJw0hFctqA+wBtYX7JotIiYJ
  /Hp/1ZPYPmAGS2pyIcBjM0hXdrzbHpRVIqViYg6P/5LpMeABel30rfOrcPCR8XKO
  7wKUbdVHxj46TPUV5KIrIdo7Za5zYhzKz5PGkuX0MrKzQflyCnj5V5iI+yqlUBEs
  bwnhuEfpSHYW6Ba62fiWEVpVNZBTQUtrvt0hF7lddvpyAfHc6/UnOhc1FsiqrHG/
  guR4VnqSMCYG8LP69gunEbX/L1q6aUiqsUC2nqrfriXfRlAoAbRwwLuMEhisb5t+
  zRsz8/xrGRBgoVJDHPvpKw4AlGyJCicIr/i40PgzWFOujHK2gcrpfejoQYK8NZrm
  1gGKlZTFCPPfR+OboKeBAoIBAQDN7m+E3k9GDvZs0WYUYz7iVpmRQsdgSG8RGzWA
  uTj8Dw7bD+7j/LJh/0A4vsCBAqoKLQarfnAR5bcrGRNotkColx+kpGYFBjbmoS1O
  qBlasyCnfKw3Layf2opgZD6FwOnHv1qs6fzc58h5gr6VF9sRrIbY7f4nhuZheRHt
  NKTJCMoOuaFpRFagbuQ4s/ZJQ+TCdx6rDYMj8oJ3ex9ERgnsLpVw6Y2lWBNDbUky
  ZPpmUG8q18xU2ztmyjSA9+2H/FaX+ecN30vkeh1Kmtd2UcCMbJ5IpphIXuRQr7XC
  l3qoz3bCc3a0XF4l5/H3KSLF2eD6drFcE6+qJLYkPgsEkQU/AoIBAQDIuH580aZZ
  aTgyxVGGeuJFdCJ2Zqgl/p+qF4qgRpv8+cKKxSbu5/2tsV8cc7Oe2parcMsFmfRf
  F60B5NKKLYw33RILjkAzjHKOR4G7L+wNH6CVWjpY4MoikylkdgAoFfaFX+QNA3yY
  B0Ee4vl6UJ41jvwaNEF9Z7vV6qB3AolN57FRWuK8BCVbbn3y+Zz3oSyOkgXgxaQ0
  2Mesi2VYueDVWh/sWPChUkV1NhUBeEMLBWgKKNW5TWT06QLAY46JtzyvC1EvOVQy
  gdzCj+KJqyAH5x4FwHrykeJKJSQQRL5SfEOw0Qo1ZtzBbX2naZKSovCu37b39N/O
  P36d04HXS9BhAoIBAQCDtLp4VSKIYSt0H1zVL0BZzB89i2MujkUSwL8wS8ZJV2wd
  6QvVnpmMGY8+e6ltGYIdLfz1E9GjcLL8inYiY2XpLXZce5SQJBBa4ryycMp+etAo
  rpEKXVjpiAE2cwaVzvL2AMmCi8hglJFgPaGcg3xlyl0YQuZo61tO/frcJe46cTeh
  wVGdnMp2o1WtelPLOfQF99+ScPrts72Doyg1J0JTXtvPMmCYXkM7vZqx82k+pLTk
  xs31e517OVnpHig578aGPptrAORuBTfUrkGdd93ZMeLt/japGp+VhzuNcApQCxge
  d3B1HBpOzhCwDgwiVB4SsnTuudyAyif/9/pd+k5LAoIBAQCr3e3QiuNZY9MPBg3M
  jKP6vHpVz4jjH6cvSYEVw+AFOQbvM+kmX9bDR0EdZ6TBvIGOwsHURgMM+YTWPkxY
  rK+Hle/BnUgz22qrkWbwFRSWGCK0P9H+EFyERmYG81Mm/8daZMUsr3Ob6XpFLCxa
  I3WUfp43Ac+hxZT8ki5cOPvAjUczVhMW0qX6KB4IUtuo3YT9fuMxl4oHBifTAnkB
  BAgUJ1t2UKGaQIvg1TIfVA5z/WkcaeK3DCIJ4wrMGXMPUKrRZ2tYeEo0BSY2ImXj
  Y3fFzIvUeP/NfES7IBpFI9ejYWvElvmayDz2Ev6ovqkWjhZwZnaQ0khgndWY5mYj
  J3OBAoIBAFColSUDfI+dJd7ISZNrFLTTps0cdUlDxwXzdG8deOh6HUFWMo8Qz96d
  17RTVHgocFU4N0wphUy6+zmptEHcOgVxQltkdbcxdP2HpRM2UE8/+SiUtjuQHhH/
  yZKDmRr6fqK7gODuSnR1lIghrVrhuUx4CJKh8d6VZMysPPM8AXbNGUHVOthBZ3z9
  wZFBRIeW+fNIJ9E8LKd9fcXK6wHvJfTeNaHp9oyTXyJxQsDhJUTEWGV1WMxLqit3
  k5e0BVRpKAW0UnR8sfI0u6ElB0aihW+7mg52ftKCfCHdnpj3GuvmZtL+O11XWIGe
  Nq5jXg2nvEI6iybEzXeOGGejVJfaP3Y=
  -----END PRIVATE KEY-----

# Varnish settings #####################################################################################################
## the packagecloud repository doesn't include bionic builds for older versions of varnish so if we're installing
## varnish 4.x or 5.x, we need to install the xenial package instead (the varnish_apt variables override the ones set
## in the geerlingguy.varnish role).
varnish_apt_repo_default: "{{ 'deb https://packagecloud.io/varnishcache/varnish' + server_varnish_version|replace('.', '') + '/' + ansible_distribution | lower + '/ ' + ansible_distribution_release + ' main' }}"
varnish_apt_repo: "{{ varnish_apt_repo_default|regex_replace('bionic', 'xenial') if server_varnish_version is search('[4|5].*') else varnish_apt_repo_default }}"
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"
varnish_listen_port: "8080"
varnish_version: '{{ server_varnish_version }}'